{{
  config(materialized = 'incremental', unique_key = 'HOST_ID')
}}

SELECT 
    HOST_ID,
    REPLACE(HOST_NAME,'_',' ') AS HOST_NAME,
    HOST_SINCE AS HOSTING_SINCE,
    IS_SUPERHOST AS IS_SUPERHOST,
    RESPONSE_RATE AS RESPONSE_RATE,
    CASE
    WHEN TRY_TO_NUMBER(REPLACE(RESPONSE_RATE, '%', '')) > 95 THEN 'VERY GOOD'
    WHEN TRY_TO_NUMBER(REPLACE(RESPONSE_RATE, '%', '')) > 80 THEN 'GOOD'
    WHEN TRY_TO_NUMBER(REPLACE(RESPONSE_RATE, '%', '')) > 60 THEN 'FAIR'
    ELSE 'POOR'
    END AS RESPONSE_RATE_QUALITY,
    CREATED_AT
FROM {{ ref('bronze_hosts') }}
